### ISSUE TITLE
Error: Не указан пароль пользователя БД

### ISSUE THREAD

**Issue by 0xB9** [RooCMS/RooCMS#56]
When installing it requires a password for the DB, would be nice if you could leave it blank for people on a localhost. Thanks! :)

**Comment by Roosso** [comment]
Sorry, but this is bad idea.
Someone from users can then accidentally forget to set password on working site.
We are not paranoid, but this is primitive security.

Does it really make it difficult? Use password on localhost?

**Comment by 0xB9** [comment]
I was referring to the DB password when installing the CMS, not the user register. 

Anyhow, yes I could setup a password for my phpMyAdmin.. this was just a suggestion as I've seen this feature in most CMS's.

**Comment by Roosso** [comment]
This idea has already been expressed by users (not GitHub members) ...

The only argument forcing me to think about introducing such function - is that this can someone sad (set users and a password on localhost)
